# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for BetBot.

Output: dist/BetBot/
  BetBot.exe        ← launcher (this spec)
  _internal/        ← Python runtime + all libraries (auto-generated by PyInstaller)
  app/              ← hot-swappable source files (copied by this spec as data)

Build:
    pyinstaller bet-bot.spec
"""

import os
import glob
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

# ── Collect customtkinter assets (fonts, themes, images) ─────────────────────
ctk_data     = collect_data_files("customtkinter")
ctk_hidden   = collect_submodules("customtkinter")

# ── Collect our app's .py files as data into app/ ────────────────────────────
# These are NOT compiled into the EXE — they stay as plain .py files so they
# can be hot-updated by the updater without re-installing the EXE.

EXCLUDES = {".git", "__pycache__", "dist", "build", ".venv", "venv",
            "installer", "tools", "exports", "data", "logs"}

app_data = []

# Root-level .py files (gui.py, updater.py, setup_wizard.py, config.py, etc.)
for f in glob.glob("*.py"):
    if f not in ("launcher.py",):   # launcher is compiled into EXE, not data
        app_data.append((f, "app"))

# version.txt
if os.path.exists("version.txt"):
    app_data.append(("version.txt", "app"))

# Subdirectory .py files (models/, scrapers/, utils/)
for root, dirs, files in os.walk("."):
    dirs[:] = [d for d in dirs if d not in EXCLUDES and not d.startswith(".")]
    rel = os.path.relpath(root, ".")
    if rel == ".":
        continue
    for fname in files:
        if fname.endswith(".py"):
            src = os.path.join(root, fname)
            dst = os.path.join("app", rel)
            app_data.append((src, dst))

# .env if it exists (user's keys — kept for bundled dev use; production has own .env)
# Do NOT bundle .env in releases — users create their own via setup wizard.
# app_data.append((".env", "app"))   # ← intentionally commented out

all_datas = ctk_data + app_data

# ── Analysis ──────────────────────────────────────────────────────────────────
a = Analysis(
    ["launcher.py"],
    pathex=["."],
    binaries=[],
    datas=all_datas,
    hiddenimports=ctk_hidden + [
        "tkinter",
        "tkinter.ttk",
        "tkinter.messagebox",
        "tkinter.filedialog",
        "sqlite3",
        "customtkinter",
        "PIL",
        "PIL.Image",
        "PIL.ImageTk",
        "requests",
        "dotenv",
        "python_dotenv",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "matplotlib",
        "numpy",
        "pandas",
        "scipy",
        "IPython",
        "jupyter",
        "notebook",
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="BetBot",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,          # no console window (GUI app)
    disable_windowed_traceback=False,
    argv_emulation=False,
    icon="assets/icon.ico" if os.path.exists("assets/icon.ico") else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="BetBot",
)
