"""
First-run setup wizard.
Shown when .env is missing or required API keys are absent.
Saves keys to .env next to the executable (or project root in dev mode).

Call:
    from setup_wizard import run_if_needed
    run_if_needed(parent_window)   # blocks until wizard is complete or skipped
"""

import os
import pathlib
import webbrowser
import customtkinter as ctk

# ── Required keys + metadata ──────────────────────────────────────────────────
_FIELDS = [
    {
        "key":      "ODDS_API_KEY",
        "label":    "The Odds API Key",
        "desc":     "Free — up to 500 requests/month. Used for all pre-game odds and value scanning.",
        "url":      "https://the-odds-api.com/#get-access",
        "placeholder": "e.g. abc123def456...",
    },
    {
        "key":      "API_FOOTBALL_KEY",
        "label":    "API-Football Key",
        "desc":     "Free — 100 requests/day. Used for live match discovery and team form stats.",
        "url":      "https://dashboard.api-football.com/register",
        "placeholder": "e.g. a1b2c3d4e5f6...",
    },
    {
        "key":      "FOOTBALL_DATA_KEY",
        "label":    "Football-Data.org Key",
        "desc":     "Free — covers top 12 European leagues. Used for pre-game team stats.",
        "url":      "https://www.football-data.org/client/register",
        "placeholder": "e.g. xxxxxxxxxxxxxxxx",
    },
    {
        "key":      "BANKROLL",
        "label":    "Starting Bankroll (€)",
        "desc":     "Your total betting bankroll. Used to calculate Kelly stake suggestions.",
        "url":      None,
        "placeholder": "e.g. 1000",
        "default":  "1000",
    },
]

_ENV_PATH = pathlib.Path(__file__).parent / ".env"

C_BG     = "#1a1a2e"
C_PANEL  = "#16213e"
C_ACCENT = "#0f3460"
C_BLUE   = "#4da6ff"
C_GREEN  = "#00b894"
C_TEXT   = "#e0e0e0"
C_DIM    = "#888"


def _load_existing() -> dict:
    vals = {}
    if _ENV_PATH.exists():
        for line in _ENV_PATH.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                vals[k.strip()] = v.strip().strip('"')
    # Also check actual env (in case already loaded by dotenv)
    for f in _FIELDS:
        if f["key"] not in vals:
            ev = os.getenv(f["key"], "")
            if ev:
                vals[f["key"]] = ev
    return vals


def _save_env(values: dict):
    lines = []
    # Keep any existing non-managed lines
    if _ENV_PATH.exists():
        managed = {f["key"] for f in _FIELDS}
        for line in _ENV_PATH.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.startswith("#"):
                k = line.split("=", 1)[0].strip()
                if k in managed:
                    continue
            lines.append(line)
    lines.append("")
    lines.append("# BetBot API Keys — generated by setup wizard")
    for f in _FIELDS:
        v = values.get(f["key"], f.get("default", ""))
        lines.append(f'{f["key"]}={v}')
    _ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def is_setup_complete() -> bool:
    existing = _load_existing()
    for f in _FIELDS:
        if f["key"] == "BANKROLL":
            continue   # optional — has default
        if not existing.get(f["key"]):
            return False
    return True


def run_if_needed(parent=None):
    """Show wizard if any required key is missing. Blocks until done."""
    if is_setup_complete():
        return
    _WizardWindow(parent).run()


# ── Wizard window ─────────────────────────────────────────────────────────────

class _WizardWindow:
    def __init__(self, parent):
        self._existing = _load_existing()
        self._entries  = {}
        self._done_flag = False

        self.win = ctk.CTkToplevel(parent) if parent else ctk.CTk()
        self.win.title("BetBot — First Time Setup")
        self.win.geometry("620x580")
        self.win.resizable(False, False)
        self.win.configure(fg_color=C_BG)
        if parent:
            self.win.grab_set()
            self.win.transient(parent)
            # Center over parent
            self.win.update_idletasks()
            px = parent.winfo_x() + parent.winfo_width()  // 2 - 310
            py = parent.winfo_y() + parent.winfo_height() // 2 - 290
            self.win.geometry(f"620x580+{px}+{py}")

        self._build()

    def _build(self):
        w = self.win

        # Header
        ctk.CTkLabel(w, text="Welcome to BetBot",
                     font=("Segoe UI", 22, "bold"), text_color=C_BLUE
                     ).pack(pady=(28, 4))
        ctk.CTkLabel(w, text="Enter your free API keys to get started.\n"
                              "Click the link next to each field to create a free account.",
                     font=("Segoe UI", 12), text_color=C_DIM, justify="center"
                     ).pack(pady=(0, 18))

        # Fields
        scroll = ctk.CTkScrollableFrame(w, fg_color=C_PANEL, corner_radius=10)
        scroll.pack(fill="both", expand=True, padx=24, pady=(0, 12))
        scroll.grid_columnconfigure(0, weight=1)

        for row_i, field in enumerate(_FIELDS):
            frame = ctk.CTkFrame(scroll, fg_color="transparent")
            frame.pack(fill="x", pady=8, padx=8)

            # Label + link row
            top_row = ctk.CTkFrame(frame, fg_color="transparent")
            top_row.pack(fill="x")
            ctk.CTkLabel(top_row, text=field["label"],
                         font=("Segoe UI", 13, "bold"), text_color=C_TEXT
                         ).pack(side="left")
            if field["url"]:
                url = field["url"]
                btn = ctk.CTkButton(top_row, text="→ Get free key",
                                    font=("Segoe UI", 11), text_color=C_BLUE,
                                    fg_color="transparent", hover_color=C_ACCENT,
                                    width=120, height=22,
                                    command=lambda u=url: webbrowser.open(u))
                btn.pack(side="right")

            ctk.CTkLabel(frame, text=field["desc"],
                         font=("Segoe UI", 11), text_color=C_DIM,
                         wraplength=540, justify="left"
                         ).pack(fill="x", pady=(2, 4))

            existing_val = self._existing.get(field["key"], field.get("default", ""))
            entry = ctk.CTkEntry(frame, placeholder_text=field["placeholder"],
                                 font=("Segoe UI", 12), height=36,
                                 fg_color=C_ACCENT, border_color=C_BLUE,
                                 text_color=C_TEXT)
            if existing_val:
                entry.insert(0, existing_val)
            entry.pack(fill="x")
            self._entries[field["key"]] = entry

        # Save button
        self._status_lbl = ctk.CTkLabel(w, text="", font=("Segoe UI", 11),
                                        text_color=C_DIM)
        self._status_lbl.pack(pady=(0, 4))

        ctk.CTkButton(w, text="Save & Launch BetBot",
                      font=("Segoe UI", 14, "bold"),
                      fg_color=C_GREEN, hover_color="#00a381",
                      height=44, corner_radius=8,
                      command=self._save).pack(padx=24, pady=(0, 20), fill="x")

    def _save(self):
        values = {}
        missing = []
        for field in _FIELDS:
            val = self._entries[field["key"]].get().strip()
            if not val and field["key"] != "BANKROLL":
                missing.append(field["label"])
            values[field["key"]] = val or field.get("default", "")

        if missing:
            self._status_lbl.configure(
                text=f"Missing: {', '.join(missing)}", text_color="#e17055")
            return

        try:
            _save_env(values)
            # Reload into os.environ for the current session
            for k, v in values.items():
                os.environ[k] = v
            self._status_lbl.configure(text="✓ Saved!", text_color=C_GREEN)
            self._done_flag = True
            self.win.after(600, self.win.destroy)
        except Exception as e:
            self._status_lbl.configure(text=f"Error: {e}", text_color="#e17055")

    def run(self):
        if hasattr(self.win, "mainloop"):
            self.win.mainloop()
        else:
            self.win.wait_window()
